services:
  postgres:
    image: postgres:15
    container_name: postgres-rotacion
    environment:
      POSTGRES_USER: ml
      POSTGRES_PASSWORD: ml
      POSTGRES_DB: mlops
    ports:
      - "5442:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped

  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"   # Spark master RPC
      - "8080:8080"   # Spark master UI
    restart: unless-stopped

  jupyter:
    build:
      context: .
      dockerfile: docker/jupyter.Dockerfile
    container_name: jupyter-rotacion
    environment:
      JUPYTER_TOKEN: keepcoding
    ports:
      - "8889:8888"   # http://localhost:8889
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - ./output:/output
      - ./notebooks:/home/jovyan/work
    depends_on:
      - postgres
      - spark-master
    restart: unless-stopped

